version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      npm-minor-patch:
        update-types: ['minor', 'patch']
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions-minor-patch:
        update-types: ['minor', 'patch']
    labels:
      - 'dependencies'
      - 'github-actions'
